ALTER TABLE entries
  ADD COLUMN IF NOT EXISTS sent_done  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS sent_doing BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS sent_todo  BOOLEAN NOT NULL DEFAULT FALSE;
